apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: pod-gpu-metrics-exporter
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: pod-gpu-metrics-exporter
      name: pod-gpu-metrics-exporter
    spec:
      nodeSelector:
        hardware-type: NVIDIAGPU
      containers:
      - image: 172.16.18.102:8443/library/pod-gpu-metrics-exporter:v1.0.1
        name: pod-nvidia-gpu-metrics-exporter
        ports:
        - name: metrics
          containerPort: 9400
          hostPort: 9400
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: pod-gpu-resources
          readOnly: true
          mountPath: /var/lib/kubelet/pod-resources
        - name: device-metrics
          readOnly: true
          mountPath: /run/prometheus
      - image: 172.16.18.102:8443/library/prometheus-dcgm-exporter:1.4.7
        name: nvidia-dcgm-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: device-metrics
          mountPath: /run/prometheus


      volumes:
      - name: pod-gpu-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
      - name: device-metrics
        emptyDir:
          medium: Memory
